// Palavras temáticas (pratos e ingredientes) com dica, usadas pela Forca e pelo
// Anagrama. Só letras A-Z sem acento (facilita o chute letra a letra e o
// embaralhado); a dica pode ter acento porque é só exibida.
const PALAVRAS = [
  { p: 'SUSHI', d: 'Clássico do balcão' },
  { p: 'SASHIMI', d: 'Fatias de peixe cru' },
  { p: 'TEMAKI', d: 'Cone de alga recheado' },
  { p: 'NIGIRI', d: 'Bolinho de arroz com fatia por cima' },
  { p: 'URAMAKI', d: 'Enrolado com o arroz por fora' },
  { p: 'HOSSOMAKI', d: 'Rolinho fino de alga' },
  { p: 'GUIOZA', d: 'Pastelzinho japonês' },
  { p: 'HARUMAKI', d: 'Rolinho primavera' },
  { p: 'TEMPURA', d: 'Empanado leve e crocante' },
  { p: 'YAKISOBA', d: 'Macarrão frito com legumes' },
  { p: 'SHIMEJI', d: 'Cogumelo na manteiga' },
  { p: 'EDAMAME', d: 'Vagem de soja cozida' },
  { p: 'SUNOMONO', d: 'Salada de pepino agridoce' },
  { p: 'GOHAN', d: 'Arroz japonês' },
  { p: 'SALMAO', d: 'Peixe alaranjado favorito' },
  { p: 'ATUM', d: 'Peixe vermelho do mar' },
  { p: 'CAMARAO', d: 'Fruto do mar rosado' },
  { p: 'POLVO', d: 'Tem oito tentáculos' },
  { p: 'LULA', d: 'Fruto do mar em anéis' },
  { p: 'WASABI', d: 'Pasta verde bem picante' },
  { p: 'GENGIBRE', d: 'Conserva rosa que limpa o paladar' },
  { p: 'SHOYU', d: 'Molho escuro salgado' },
  { p: 'HASHI', d: 'Talher de madeira' },
  { p: 'COMBINADO', d: 'Seleção variada de peças' },
  { p: 'TERIYAKI', d: 'Molho agridoce brilhante' },
  { p: 'ROBATA', d: 'Grelhado na brasa' },
  { p: 'NORI', d: 'Alga que envolve o sushi' },
  { p: 'CEVICHE', d: 'Peixe marinado no limão' },
  { p: 'HOTROLL', d: 'Enrolado empanado servido quente' },
  { p: 'FILADELFIA', d: 'Leva cream cheese' },
  { p: 'ARROZ', d: 'A base de tudo' },
  { p: 'ALGA', d: 'Folha que envolve o temaki' },
  { p: 'PEIXE', d: 'Estrela do cardápio' },
  { p: 'KANI', d: 'Bastão sabor caranguejo' },
  { p: 'SKIN', d: 'Pele de salmão crocante' },
  { p: 'MAKI', d: 'Enrolado tradicional' },
  { p: 'SOBA', d: 'Macarrão de trigo sarraceno' },
  { p: 'UDON', d: 'Macarrão japonês grosso' },
  { p: 'MISO', d: 'Pasta de soja fermentada' },
  { p: 'TOFU', d: 'Queijo de soja' },
  { p: 'NABO', d: 'Raiz branca ralada' },
  { p: 'NIRA', d: 'Verdura da guioza' },
  { p: 'SAQUE', d: 'Bebida japonesa de arroz' },
  { p: 'DASHI', d: 'Caldo base da culinária' },
  { p: 'TATA', d: 'A nossa casa' },
]

export default PALAVRAS
